baseURL = "https://tangelov.me"
languageCode = "es"
DefaultContentLanguage = "es"
title = "Estando en las nubes"
uglyurls = true

theme = "Lanyon"

[permalinks]
  posts = ":section/:slug/"

[languages]
  [languages.es]
    title = "Estando en las nubes"
    languageName = "Espa√±ol"
    weight = 1

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"
